### ISSUE TITLE
看到这里的冒险岛教程, 满满的回忆

### ISSUE THREAD

**Issue by thxiami** [kms-docs/starter#1]
在看博主 blog 的 [2019 总结](https://evila.me/#/posts/2019-summary)时, 意外看到冒险岛三个字, 挺意外的, 本来我是看前端开发技术和 MacOS 软件推荐的,怎么跑偏了呢~~hhhh
好久没玩冒险岛了, 初中入坑, V079 版本是我最后的坚守了, 那时候还没四转, 然后国服最高级的玩家155 级好像. 我周末手动升级, 玩了很久还是卡在了 40+级, 刷蜈蚣 bug 倒是挺有意思的, 升了好几级. 但是还是不得不吐槽下国服升级太慢, 除此之外还是留下了很多美好的回忆. 废弃都市跳箱子, 拿卷轴卖黑心商人赚的第一桶金(好像是铠甲敏捷卷轴最贵),  玩具城跳箱子(找盗贼职业投过关卡可以快速过关)

后面读大学了, 玩过一个私服, 叫木木冒险岛, 也是 V079 版本的, 充了一点钱, 在国服体验不到的在这里都体验了很多, 刷蘑菇王, 刷蝙蝠怪, 刷扎昆, 带扎昆帽. 还能转生, 体验不同职业, 蛮有意思的

最后一次是在 15 年, 跟朋友玩了台服, 但是职业五花八门, 已经看不懂了, 而且玩游戏的人们都不在当年了. 

看到博主玩韩服, 我在想跟大家都英文交流吗? hhh

**Comment by 2nthony** [comment]
基本不会和韩国玩家交流的，因为怕被举报。毕竟我们是「偷渡客」，老的账号都是盗用或者伪造身份信息来注册账号，当然也有友好的韩国玩家会一起玩。

而且有国人群；大部分求助或交易可以内销解决。

**Comment by thxiami** [comment]
跟玩台服时候有点像, 国人内部有群, 还有金币工作室

**Comment by 2nthony** [comment]
台服也玩过，没钱真的难玩

韩服还好，能完全白手起家

**Comment by thxiami** [comment]
下次直播走起哈, 昨天去你直播间看了下, 很久没播了啊~

**Comment by 2nthony** [comment]
已经不播了，我的号也由于太久没玩被🔐了

**Comment by thxiami** [comment]
那就只能留点回忆啦~~

**Comment by 2nthony** [comment]
只有一个02-29号的录播（周常boss，还挺有意义

**Comment by thxiami** [comment]
> 02-29号的录播（周常boss，还挺有意义

我去看看

**Comment by thxiami** [comment]
现在的技能好酷炫, 而且还能单刷 BOSS, 不过看起来像是弱化版的, 扎昆都没召唤小兵. 我看刷扎昆时候网络卡了下就跪了, 哈哈 小墓碑掉下来, 好起来好熟悉~~

**Comment by 2nthony** [comment]
那是侠盗，确实技能还不错，但是没了该怀念的味道

所以这1个多小时的录播，基本上就是每周做的事情

**Comment by thxiami** [comment]
那就当每周休闲娱乐了~~也蛮好的
写写代码,  娱乐娱乐.
博主的2020 自由职业开启了吗, 等你更博
